{
 "title": "Cluster_ overview",
 "tags": [ "ibm-mq-integration" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ibmmq_qmgr_commit_count,job)"
    }
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": {
     "query": "label_values(ibmmq_qmgr_commit_count,mq_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Clusters",
   "type": "stat",
   "description": "The unique number of clusters being reported.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_qmgr_commit_count) by (mq_cluster))",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queue managers",
   "type": "stat",
   "description": "The unique number of queue managers in the cluster being reported.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_qmgr_commit_count) by (qmgr, mq_cluster))"
    }
   ]
  },
  {
   "title": "Queue operations",
   "type": "piechart",
   "description": "The number of queue operations of the cluster. ",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_queue_mqset_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"}",
     "legendFormat": "MQSET"
    },
    {
     "expr": "ibmmq_queue_mqinq_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"}",
     "legendFormat": "MQINQ"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqget_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQGET"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqopen_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQOPEN"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqclose_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQCLOSE"
    },
    {
     "expr": "sum by (mq_cluster) (ibmmq_queue_mqput_mqput1_count{mq_cluster=~\"$mq_cluster\", job=~\"$job\"})",
     "legendFormat": "MQPUT/MQPUT1"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "The unique number of topics in the cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_topic_messages_received) by (topic, mq_cluster))",
     "legendFormat": "{{job}} - {{mq_cluster}}"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "description": "The unique number of queues in the cluster.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_queue_depth) by (queue, mq_cluster))"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table",
   "description": "The status of the cluster.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "ibmmq_cluster_suspend{}", "legendFormat": "{{job}} - {{mq_cluster}}" }
   ]
  },
  {
   "title": "Queue manager status",
   "type": "table",
   "description": "The queue managers of the cluster displayed in a table.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "ibmmq_qmgr_status{}" }
   ]
  },
  {
   "title": "Transmission queue time",
   "type": "table",
   "description": "The time it takes for the messages to get through the transmission queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ibmmq_channel_xmitq_time_short{}"
    },
    {
     "expr": "Ibmmq_channel_xmitq_time_long{}"
    }
   ]
  }
 ]
}