{
 "title": "Queue overview",
 "tags": [ "ibm-mq-integration" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ibmmq_queue_average_queue_time_seconds,job)"
    }
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": {
     "query": "label_values(ibmmq_queue_average_queue_time_seconds{job=~\"$job\"},mq_cluster)"
    }
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": {
     "query": "label_values(ibmmq_queue_average_queue_time_seconds{job=~\"$job\"},qmgr)"
    }
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": {
     "query": "label_values(ibmmq_queue_average_queue_time_seconds,queue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average queue time",
   "type": "timeseries",
   "description": "The average amount of time a message spends in the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_queue_average_queue_time_seconds{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Expired messages",
   "type": "timeseries",
   "description": "The amount of expired messages in the queue.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ibmmq_queue_expired_messages{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Depth",
   "type": "timeseries",
   "description": "The number of active messages in the queue.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "ibmmq_queue_depth{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - {{queue}}"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "timeseries",
   "description": "The number of queue operations of the queue manager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "ibmmq_queue_mqset_count{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQSET"
    },
    {
     "expr": "ibmmq_queue_mqinq_count{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQINQ"
    },
    {
     "expr": "ibmmq_queue_mqget_count{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQGET"
    },
    {
     "expr": "ibmmq_queue_mqopen_count{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQOPEN"
    },
    {
     "expr": "ibmmq_queue_mqclose_count{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQCLOSE"
    },
    {
     "expr": "ibmmq_queue_mqput_mqput1_count{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQPUT/MQPUT1"
    }
   ]
  },
  {
   "title": "Operation throughput",
   "type": "timeseries",
   "description": "The amount of throughput going through the queue via MQGETs and MQPUTs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "ibmmq_queue_mqget_bytes{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQGET"
    },
    {
     "expr": "ibmmq_queue_mqput_bytes{job=~\"$job\", mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", queue=~\"$queue\"}",
     "legendFormat": "{{qmgr}} - {{queue}} - MQPUT"
    }
   ]
  }
 ]
}