{
 "title": "Queue Manager overview",
 "tags": [ "ibm-mq-integration" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "prometheus_logs", "label": "Loki Datasource", "query": "loki" },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ibmmq_topic_messages_received,job)"
    }
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": {
     "query": "label_values(ibmmq_topic_messages_received,mq_cluster)"
    }
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": {
     "query": "label_values(ibmmq_topic_messages_received{mq_cluster=~\"$mq_cluster\"},qmgr)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active listeners",
   "type": "stat",
   "description": "The number of active listeners for the queue manager.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_active_listeners{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "stat",
   "description": "The number of active connections for the queue manager.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_connection_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "stat",
   "description": "The unique number of queues being managed by the queue manager.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(ibmmq_queue_depth) by (queue, mq_cluster, qmgr))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "The system/user CPU usage of the queue manager.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_user_cpu_time_percentage{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "user - {{mq_cluster}} - {{qmgr}}"
    },
    {
     "expr": "ibmmq_qmgr_system_cpu_time_percentage{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "system - {{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Estimated memory utilization",
   "type": "timeseries",
   "description": "The estimated memory usage of the queue managers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(ibmmq_qmgr_ram_total_estimate_for_queue_manager_bytes{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}/ibmmq_qmgr_ram_total_bytes{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}) * 100",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Queue manager status",
   "type": "table",
   "description": "A table showing the status and uptime of the queue manager.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_uptime{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "Uptime"
    },
    {
     "expr": "ibmmq_qmgr_status{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The disk allocated to the queue manager that is being used.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_queue_manager_file_system_in_use_bytes{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Publish throughput",
   "type": "timeseries",
   "description": "The amount of data being pushed from the queue manager to subscribers.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_published_to_subscribers_bytes{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Published messages",
   "type": "timeseries",
   "description": "The number of messages being published by the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_published_to_subscribers_message_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "description": "The commits of the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_commit_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Expired messages",
   "type": "timeseries",
   "description": "The expired messages of the queue manager.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "ibmmq_qmgr_expired_message_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Queue operations",
   "type": "timeseries",
   "description": "The number of queue operations of the queue manager. ",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "targets": [
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqset_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQSET"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqinq_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQINQ"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqget_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQGET"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqopen_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQOPEN"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqclose_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQCLOSE"
    },
    {
     "expr": "sum by (mq_cluster, qmgr, job) (ibmmq_queue_mqput_mqput1_count{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"})",
     "legendFormat": "{{mq_cluster}} - {{qmgr}} - MQPUT/MQPUT1"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Log latency",
   "type": "timeseries",
   "description": "The recent latency of log writes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_log_write_latency_seconds{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Log usage",
   "type": "timeseries",
   "description": "The amount of data on the filesystem occupied by queue manager logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "ibmmq_qmgr_log_in_use_bytes{mq_cluster=~\"$mq_cluster\", qmgr=~\"$qmgr\", job=~\"$job\"}",
     "legendFormat": "{{mq_cluster}} - {{qmgr}}"
    }
   ]
  },
  {
   "title": "Error logs",
   "type": "logs",
   "description": "Recent error logs from the queue manager.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "{job=~\"$job\", filename=~\"/var/mqm/qmgrs/.*/errors/.*LOG\", qmgr=~\"$qmgr\"} |= ``"
    }
   ]
  }
 ]
}