{
 "title": "Topics overview",
 "tags": [ "ibm-mq-integration" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(ibmmq_topic_messages_received,job)"
    }
   },
   {
    "name": "mq_cluster",
    "label": "MQ cluster",
    "query": {
     "query": "label_values(ibmmq_topic_messages_received{job=~\"$job\"},mq_cluster)"
    }
   },
   {
    "name": "qmgr",
    "label": "Queue manager",
    "query": {
     "query": "label_values(ibmmq_topic_messages_received{mq_cluster=~\"$mq_cluster\"},qmgr)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(ibmmq_topic_subscriber_count{qmgr=~\"$qmgr\",topic!~\"SYSTEM.*|\\\\$SYS.*|\"},topic)"
    }
   },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": {
     "query": "label_values(ibmmq_subscription_messsages_received{qmgr=~\"$qmgr\",subscription!~\"SYSTEM.*|\"},subscription)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Topic messages received",
   "type": "timeseries",
   "description": "Received messages per topic.",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ibmmq_topic_messages_received{job=~\"$job\",mq_cluster=~\"$mq_cluster\",qmgr=~\"$qmgr\",topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Time since last message",
   "type": "timeseries",
   "description": "The time since the topic last got a message.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "ibmmq_topic_time_since_msg_received{job=~\"$job\",mq_cluster=~\"$mq_cluster\",qmgr=~\"$qmgr\",topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic subscribers",
   "type": "timeseries",
   "description": "The number of subscribers per topic.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ibmmq_topic_subscriber_count{job=~\"$job\",mq_cluster=~\"$mq_cluster\",qmgr=~\"$qmgr\",topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topic publishers",
   "type": "timeseries",
   "description": "The number of publishers per topic.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ibmmq_topic_publisher_count{job=~\"$job\",mq_cluster=~\"$mq_cluster\",qmgr=~\"$qmgr\",topic=~\"$topic\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Subscription messages received",
   "type": "timeseries",
   "description": "The number of messages a subscription receives.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ibmmq_subscription_messsages_received{job=~\"$job\",mq_cluster=~\"$mq_cluster\",qmgr=~\"$qmgr\",subscription=~\"$subscription\"}",
     "legendFormat": "{{subscription}}"
    }
   ]
  },
  {
   "title": "Subscription status",
   "type": "table",
   "description": "A table for at a glance information about a subscription.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "ibmmq_subscription_time_since_message_published{job=~\"$job\",mq_cluster=~\"$mq_cluster\",qmgr=~\"$qmgr\",subscription=~\"$subscription\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}